//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _out {
            get {
                object obj = ResourceManager.GetObject("out", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Железобетон (2500 кг/м3)|1,92|2,04|17,98|18,95
        ///Бетон на гравии или щебне из природного камня (2400 кг/м3)|1,74|1,86|16,77|17,88
        ///Туфобетон (1800 кг/м3)|0,87|0,99|11,38|12,79
        ///Туфобетон (1600 кг/м3)|0,7|0,81|9,62|10,91
        ///Туфобетон (1400 кг/м3)|0,52|0,58|7,76|8,63
        ///Туфобетон (1200 кг/м3)|0,41|0,47|6,38|7,2
        ///Пемзобетон (1600 кг/м3)|0,6|0,68|8,54|9,3
        ///Пемзобетон (1400 кг/м3)|0,49|0,54|7,1|7,76
        ///Пемзобетон (1200 кг/м3)|0,4|0,43|5,94|6,41
        ///Пемзобетон (1000 кг/м3)|0,3|0,34|4,69|5,2
        ///Пемзобетон (800 кг/м3)|0,22|0,2 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Nmaterial {
            get {
                return ResourceManager.GetString("Nmaterial", resourceCulture);
            }
        }
    }
}
